[package]
name = "rust_voxels"
version = "0.1.0"
authors = ["Jim <jim4m80@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"